const LOCAL_API_URL='http://localhost:8080/api';
const PRODUCTION_API_URL='https://gym-back-end-stmi.onrender.com/api';
const API_URL=(location.hostname==='localhost'||location.hostname==='127.0.0.1')?LOCAL_API_URL:PRODUCTION_API_URL;
const $=id=>document.getElementById(id);
const memberForm=$('memberForm'),trainerForm=$('trainerForm'),sessionForm=$('sessionForm');
const memberList=$('memberList'),trainerList=$('trainerList'),sessionTable=$('sessionTable');
const memberId=$('memberId'),memberFirstName=$('memberFirstName'),memberLastName=$('memberLastName'),memberDocument=$('memberDocument'),memberPhone=$('memberPhone'),memberEmail=$('memberEmail'),memberMembership=$('memberMembership'),memberFormTitle=$('memberFormTitle'),memberSubmitBtn=$('memberSubmitBtn'),cancelMemberEditBtn=$('cancelMemberEditBtn');
const trainerId=$('trainerId'),trainerFirstName=$('trainerFirstName'),trainerLastName=$('trainerLastName'),trainerSpecialty=$('trainerSpecialty'),trainerPhone=$('trainerPhone'),trainerEmail=$('trainerEmail'),trainerFormTitle=$('trainerFormTitle'),trainerSubmitBtn=$('trainerSubmitBtn'),cancelTrainerEditBtn=$('cancelTrainerEditBtn');
const sessionId=$('sessionId'),sessionDate=$('sessionDate'),sessionMember=$('sessionMember'),sessionTrainer=$('sessionTrainer'),trainingType=$('trainingType'),durationMinutes=$('durationMinutes'),sessionNotes=$('sessionNotes'),sessionFormTitle=$('sessionFormTitle'),sessionSubmitBtn=$('sessionSubmitBtn'),cancelSessionEditBtn=$('cancelSessionEditBtn');
let members=[],trainers=[],sessions=[];
async function request(endpoint,options={}){const res=await fetch(`${API_URL}${endpoint}`,{headers:{'Content-Type':'application/json'},...options});if(!res.ok){let msg='Error en la petición al backend.';try{const e=await res.json();msg=e.message||e[Object.keys(e)[0]]||msg}catch{}throw new Error(msg)}return res.status===204?null:res.json()}
function toast(msg,type='success'){const box=$('toastBox'),el=document.createElement('div');el.className=`app-toast ${type}`;el.innerHTML=`<strong>${type==='success'?'Listo':'Atención'}</strong><div>${msg}</div>`;box.appendChild(el);setTimeout(()=>el.remove(),3500)}
function fullName(p){return `${p.firstName} ${p.lastName}`}function fmtDate(v){return v?new Date(v).toLocaleString('es-CO'):'Sin fecha'}function toLocal(v){return v?v.substring(0,16):''}
async function loadData(){try{members=await request('/members');trainers=await request('/trainers');sessions=await request('/training-sessions');renderAll()}catch(e){toast('No se pudo conectar con el backend. Revisa la API o la URL de producción.','error')}}
function renderAll(){renderStats();renderMembers();renderTrainers();renderSessions()}function renderStats(){$('membersCount').textContent=members.length;$('trainersCount').textContent=trainers.length;$('sessionsCount').textContent=sessions.length}
function renderMembers(){memberList.innerHTML='';sessionMember.innerHTML='<option value="">Seleccione miembro</option>';if(!members.length){memberList.innerHTML='<div class="empty-state">No hay miembros registrados.</div>';return}members.forEach(m=>{memberList.innerHTML+=`<article class="smart-list-item"><div><h4>${fullName(m)}</h4><p>Doc: ${m.documentNumber} · ${m.phone}</p><p>${m.email} · Membresía: ${m.membershipType}</p></div><div class="item-actions"><button class="btn btn-warning btn-icon" onclick="editMember(${m.id})"><i class="bi bi-pencil-square"></i></button><button class="btn btn-danger btn-icon" onclick="deleteMember(${m.id})"><i class="bi bi-trash3"></i></button></div></article>`;sessionMember.innerHTML+=`<option value="${m.id}">${fullName(m)}</option>`})}
function renderTrainers(){trainerList.innerHTML='';sessionTrainer.innerHTML='<option value="">Seleccione entrenador</option>';if(!trainers.length){trainerList.innerHTML='<div class="empty-state">No hay entrenadores registrados.</div>';return}trainers.forEach(t=>{trainerList.innerHTML+=`<article class="smart-list-item"><div><h4>${fullName(t)}</h4><p>${t.specialty} · ${t.phone}</p><p>${t.email}</p></div><div class="item-actions"><button class="btn btn-warning btn-icon" onclick="editTrainer(${t.id})"><i class="bi bi-pencil-square"></i></button><button class="btn btn-danger btn-icon" onclick="deleteTrainer(${t.id})"><i class="bi bi-trash3"></i></button></div></article>`;sessionTrainer.innerHTML+=`<option value="${t.id}">${fullName(t)} - ${t.specialty}</option>`})}
function renderSessions(){sessionTable.innerHTML='';if(!sessions.length){sessionTable.innerHTML='<tr><td colspan="8"><div class="empty-state">No hay sesiones programadas todavía.</div></td></tr>';return}sessions.forEach(s=>{sessionTable.innerHTML+=`<tr><td>${s.id}</td><td>${fmtDate(s.sessionDate)}</td><td>${fullName(s.member)}</td><td>${fullName(s.trainer)}</td><td>${s.trainingType}</td><td>${s.durationMinutes} min</td><td>${s.notes||'Sin notas'}</td><td><div class="d-flex gap-2"><button class="btn btn-sm btn-warning" onclick="editSession(${s.id})"><i class="bi bi-pencil-square"></i></button><button class="btn btn-sm btn-danger" onclick="deleteSession(${s.id})"><i class="bi bi-trash3"></i></button></div></td></tr>`})}
memberForm.addEventListener('submit',async e=>{e.preventDefault();GymValidation.clearForm(memberForm);let ok=true;ok=GymValidation.lettersOnly(memberFirstName,'El nombre')&&ok;ok=GymValidation.lettersOnly(memberLastName,'El apellido')&&ok;ok=GymValidation.numeric(memberDocument,'El documento')&&ok;ok=GymValidation.numeric(memberPhone,'El celular')&&ok;ok=GymValidation.email(memberEmail)&&ok;ok=GymValidation.lettersOnly(memberMembership,'La membresía',3,60)&&ok;if(!ok)return toast('Revisa los campos del formulario de miembros.','error');const data={firstName:memberFirstName.value.trim(),lastName:memberLastName.value.trim(),documentNumber:memberDocument.value.trim(),phone:memberPhone.value.trim(),email:memberEmail.value.trim(),membershipType:memberMembership.value.trim()};try{if(memberId.value){await request(`/members/${memberId.value}`,{method:'PUT',body:JSON.stringify(data)});toast('Miembro actualizado.')}else{await request('/members',{method:'POST',body:JSON.stringify(data)});toast('Miembro registrado.')}resetMemberForm();await loadData()}catch(err){toast(err.message,'error')}});
function editMember(id){const m=members.find(x=>x.id===id);if(!m)return;memberId.value=m.id;memberFirstName.value=m.firstName;memberLastName.value=m.lastName;memberDocument.value=m.documentNumber;memberPhone.value=m.phone;memberEmail.value=m.email;memberMembership.value=m.membershipType;memberFormTitle.innerHTML='<i class="bi bi-pencil-square"></i> Actualizar miembro';memberSubmitBtn.textContent='Actualizar miembro';cancelMemberEditBtn.classList.remove('hidden');memberForm.scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteMember(id){const m=members.find(x=>x.id===id);if(!confirm(`¿Eliminar a ${m?fullName(m):'este miembro'}?`))return;try{await request(`/members/${id}`,{method:'DELETE'});toast('Miembro eliminado.');await loadData()}catch{toast('No se pudo eliminar. Puede tener sesiones asociadas.','error')}}
function resetMemberForm(){memberForm.reset();memberId.value='';memberFormTitle.innerHTML='<i class="bi bi-person-plus-fill"></i> Registrar miembro';memberSubmitBtn.textContent='Guardar miembro';cancelMemberEditBtn.classList.add('hidden');GymValidation.clearForm(memberForm)}
trainerForm.addEventListener('submit',async e=>{e.preventDefault();GymValidation.clearForm(trainerForm);let ok=true;ok=GymValidation.lettersOnly(trainerFirstName,'El nombre')&&ok;ok=GymValidation.lettersOnly(trainerLastName,'El apellido')&&ok;ok=GymValidation.lettersOnly(trainerSpecialty,'La especialidad',3,100)&&ok;ok=GymValidation.numeric(trainerPhone,'El celular')&&ok;ok=GymValidation.email(trainerEmail)&&ok;if(!ok)return toast('Revisa los campos del formulario de entrenadores.','error');const data={firstName:trainerFirstName.value.trim(),lastName:trainerLastName.value.trim(),specialty:trainerSpecialty.value.trim(),phone:trainerPhone.value.trim(),email:trainerEmail.value.trim()};try{if(trainerId.value){await request(`/trainers/${trainerId.value}`,{method:'PUT',body:JSON.stringify(data)});toast('Entrenador actualizado.')}else{await request('/trainers',{method:'POST',body:JSON.stringify(data)});toast('Entrenador registrado.')}resetTrainerForm();await loadData()}catch(err){toast(err.message,'error')}});
function editTrainer(id){const t=trainers.find(x=>x.id===id);if(!t)return;trainerId.value=t.id;trainerFirstName.value=t.firstName;trainerLastName.value=t.lastName;trainerSpecialty.value=t.specialty;trainerPhone.value=t.phone;trainerEmail.value=t.email;trainerFormTitle.innerHTML='<i class="bi bi-pencil-square"></i> Actualizar entrenador';trainerSubmitBtn.textContent='Actualizar entrenador';cancelTrainerEditBtn.classList.remove('hidden');trainerForm.scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteTrainer(id){const t=trainers.find(x=>x.id===id);if(!confirm(`¿Eliminar a ${t?fullName(t):'este entrenador'}?`))return;try{await request(`/trainers/${id}`,{method:'DELETE'});toast('Entrenador eliminado.');await loadData()}catch{toast('No se pudo eliminar. Puede tener sesiones asociadas.','error')}}
function resetTrainerForm(){trainerForm.reset();trainerId.value='';trainerFormTitle.innerHTML='<i class="bi bi-person-workspace"></i> Registrar entrenador';trainerSubmitBtn.textContent='Guardar entrenador';cancelTrainerEditBtn.classList.add('hidden');GymValidation.clearForm(trainerForm)}
sessionForm.addEventListener('submit',async e=>{e.preventDefault();GymValidation.clearForm(sessionForm);let ok=true;ok=GymValidation.future(sessionDate)&&ok;ok=GymValidation.select(sessionMember,'un miembro')&&ok;ok=GymValidation.select(sessionTrainer,'un entrenador')&&ok;ok=GymValidation.lettersOnly(trainingType,'El tipo de entrenamiento',3,100)&&ok;ok=GymValidation.duration(durationMinutes)&&ok;ok=GymValidation.maxLength(sessionNotes,'Las notas',255)&&ok;if(!ok)return toast('Revisa los campos del formulario de sesiones.','error');const data={sessionDate:sessionDate.value,trainingType:trainingType.value.trim(),durationMinutes:Number(durationMinutes.value),notes:sessionNotes.value.trim(),memberId:Number(sessionMember.value),trainerId:Number(sessionTrainer.value)};try{if(sessionId.value){await request(`/training-sessions/${sessionId.value}`,{method:'PUT',body:JSON.stringify(data)});toast('Sesión actualizada.')}else{await request('/training-sessions',{method:'POST',body:JSON.stringify(data)});toast('Sesión programada.')}resetSessionForm();await loadData()}catch(err){toast(err.message,'error')}});
function editSession(id){const s=sessions.find(x=>x.id===id);if(!s)return;sessionId.value=s.id;sessionDate.value=toLocal(s.sessionDate);sessionMember.value=s.member.id;sessionTrainer.value=s.trainer.id;trainingType.value=s.trainingType;durationMinutes.value=s.durationMinutes;sessionNotes.value=s.notes||'';sessionFormTitle.innerHTML='<i class="bi bi-pencil-square"></i> Actualizar sesión';sessionSubmitBtn.textContent='Actualizar sesión';cancelSessionEditBtn.classList.remove('hidden');sessionForm.scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteSession(id){if(!confirm('¿Eliminar esta sesión?'))return;try{await request(`/training-sessions/${id}`,{method:'DELETE'});toast('Sesión eliminada.');await loadData()}catch(err){toast(err.message,'error')}}
function resetSessionForm(){sessionForm.reset();sessionId.value='';sessionFormTitle.innerHTML='<i class="bi bi-calendar2-plus-fill"></i> Programar sesión';sessionSubmitBtn.textContent='Guardar sesión';cancelSessionEditBtn.classList.add('hidden');GymValidation.clearForm(sessionForm)}
cancelMemberEditBtn.onclick=resetMemberForm;cancelTrainerEditBtn.onclick=resetTrainerForm;cancelSessionEditBtn.onclick=resetSessionForm;$('refreshBtn').onclick=loadData;loadData();
